[package]
name = "platformtreeb"
version = "0.1.0"
authors = ["Zinc Developers <zinc@github.com>"]

[lib]
name = "platformtreeb"

[features]
mcu_lpc11xx = []
mcu_lpc17xx = []
mcu_stm32f1 = []
mcu_stm32f4 = []
mcu_stm32f7 = []
mcu_stm32l1 = []
mcu_k20 = []

[dependencies]
